// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0DodXEj9oUPhp4Xrz5xQl5xTTlB-Sx5g',
    appId: '1:988478593263:web:b91b958f9c607366c2a31a',
    messagingSenderId: '988478593263',
    projectId: 'pashuapp-9363b',
    authDomain: 'pashuapp-9363b.firebaseapp.com',
    storageBucket: 'pashuapp-9363b.firebasestorage.app',
    measurementId: 'G-M6VXKXBXD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-k12UBzKKW-fKhUmTwktiwySOiE8i--A',
    appId: '1:988478593263:android:9690d028f1291e0ac2a31a',
    messagingSenderId: '988478593263',
    projectId: 'pashuapp-9363b',
    storageBucket: 'pashuapp-9363b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1cBVqv2S6jZmhC_IYG6q3ZCXXFNadcl8',
    appId: '1:988478593263:ios:9427cc60bcd91a9ec2a31a',
    messagingSenderId: '988478593263',
    projectId: 'pashuapp-9363b',
    storageBucket: 'pashuapp-9363b.firebasestorage.app',
    iosBundleId: 'com.example.pashuu',
  );
}
